---

# Installation:
- name: LogDNA Agent Repository
  yum_repository:
    name: logdna-agent
    description: LogDNA Agent YUM Package
    baseurl: http://repo.logdna.com/el6/
    gpgcheck: false

- name: Install LogDNA Agent
  yum:
    state: "{{ agent_install_state }}"
    name: logdna-agent
